spring.application.name=sciinovdbms
spring.data.mongodb.uri=mongodb+srv://subbaraodb:subbarao123@subbaraodb.3k9ymva.mongodb.net/subbaraodb?appName=subbaraodb
spring.data.mongodb.auto-index-creation=true
spring.port=8080
# JWT Configuration
app.jwt.secret=5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
app.jwt.expiration-ms=86400000

# File Upload
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html